#=========================================================================
# gh-actions-run-tests.yml
#=========================================================================

name: Run Tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: "Install Verilator"
        run: |
          wget https://github.com/cornell-brg/verilator-travisci-cache/raw/master/verilator-travis-4.036.tar.gz
          tar -C ${HOME} -xzf verilator-travis-4.036.tar.gz
          export VERILATOR_ROOT=${HOME}/verilator
          export PATH=${VERILATOR_ROOT}/bin:${PATH}
          export PYMTL_VERILATOR_INCLUDE_DIR=${VERILATOR_ROOT}/share/verilator/include
          verilator --version

      - name: "Install Python Dependencies"
        run: |
          python -VV
          pip install -U git+https://github.com/pymtl/pymtl3.git@ece5745-2021
          pip list

      - name: "Run PyMTL3 Tests"
        run: |
          mkdir -p build
          cd build
          pytest .. --verbose

      - name: "Run PyMTL3 Tests with --test-verilog"
        run: |
          mkdir -p build-verilog
          cd build-verilog
          pytest .. --verbose


