
name: GitHub Actions PyMTL3
on: [push]
jobs:

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: python-version: '3.7'
      - name: "Install Dependencies"
        run: |
          python -VV
          pip install -U git+https://github.com/pymtl/pymtl3.git@ece5745-2021
          pip list
      - name: "Run Tests"
          mkdir -p build
          cd build
          pytest .. --verbose

